name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-sphinx-docs:
    uses: ./.github/workflows/sphinx-doc-build.yml

  build-doxygen-docs:
    uses: ./.github/workflows/doxygen-build.yml

  build-code-coverage:
    uses: ./.github/workflows/code-coverage.yml

  publish-docs:
    runs-on: ubuntu-latest
    needs: [build-sphinx-docs, build-doxygen-docs, build-code-coverage]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Sphinx documentation
        uses: actions/download-artifact@v4
        with:
          name: sphinx_docs
          path: ./doc/github_pages

      - name: Unzip Sphinx documentation
        working-directory: ./doc/github_pages
        run: |
          unzip sphinx_docs.zip
          rm sphinx_docs.zip

      - name: Download doxygen documentation
        uses: actions/download-artifact@v4
        with:
          name: doxygen_docs
          path: ./doc/github_pages

      - name: Unzip doxygen documentation
        working-directory: ./doc/github_pages
        run: |
          unzip doxygen_docs.zip
          rm doxygen_docs.zip

      - name: Download Code coverage report
        uses: actions/download-artifact@v4
        with:
          name: code_coverage
          path: ./doc/github_pages

      - name: Unzip Code coverage report
        working-directory: ./doc/github_pages
        run: |
          unzip code_coverage.zip
          rm code_coverage.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/github_pages
          force_orphan: true
